// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: go_crm_user_c.sql

package database

import (
	"context"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT usr_email, usr_id FROM ` + "`" + `go_crm_user` + "`" + ` WHERE usr_email = ? LIMIT 1
`

type GetUserByEmailRow struct {
	UsrEmail string
	UsrID    uint32
}

func (q *Queries) GetUserByEmail(ctx context.Context, usrEmail string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, usrEmail)
	var i GetUserByEmailRow
	err := row.Scan(&i.UsrEmail, &i.UsrID)
	return i, err
}

const updateUserStatusByUserID = `-- name: UpdateUserStatusByUserID :exec
UPDATE ` + "`" + `go_crm_user` + "`" + `
SET usr_status = ?, usr_updated_at = ?
WHERE usr_id = ?
`

type UpdateUserStatusByUserIDParams struct {
	UsrStatus    bool
	UsrUpdatedAt int32
	UsrID        uint32
}

func (q *Queries) UpdateUserStatusByUserID(ctx context.Context, arg UpdateUserStatusByUserIDParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatusByUserID, arg.UsrStatus, arg.UsrUpdatedAt, arg.UsrID)
	return err
}
